server:
  port: 8080
---
spring:  application:    name: ms-greeting
---
ms-greeting:
  greeting: "Ciao"
  default-value: "Mondo"
---
management:  endpoints:    web:      exposure:        include:        - "*"